[package]
name = "mine_sweeper"
version = "0.1.0"
authors = ["Alexander Öberg <stativetroller7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.*"